disabled_rules:
  - trailing_whitespace

excluded:
  - CloudNotes/SceneDelegate.swift
  - CloudNotes/AppDelegate.swift

opt_in_rules:
  - indentation_width

indentation_width:
    indentation_width: 2
