# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CloudNotes' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftLint', '0.45.1'
  pod 'SwiftyDropbox', '8.2.1'

  # Pods for CloudNotes

  target 'CloudNotesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CloudNotesUITests' do
    # Pods for testing
  end

end
