# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CloudNotes' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CloudNotes

  pod 'SwiftyDropbox'

  target 'CloudNotesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CloudNotesUITests' do
    # Pods for testing
  end

end
